version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=us-east-1
      - DATA_DIR=/tmp/localstack/data
    ports:
      - "4566:4566"  # Edge port for all services
    volumes:
      - localstack_data:/var/lib/localstack
      - ./localstack-init:/etc/localstack/init/ready.d


volumes:
  db_data:
  localstack_data: