export enum SegmentPlace {
  Like = "Like",
  Dislike = "Dislike",
  Favorite = "Favorite",
  Share = "Share",
  JumpIn = "Jump In",
  Join = "Join",
  FilterChange = "Filter Change",
  OverviewHightRated = "Overview Hight Rated",
  OverviewMyFavorites = "Overview My Favorites",
  OverviewRecentlyUpdated = "Overview Recently Updated",
  OverviewPointsOfInterest = "Overview Points Of Interest",
  MyPlace = "My Place",
  MyPlaceChangePagination = "My Place Change Pagination",
  Place = "Place",
  Places = "Places",
  PlacesChangePagination = "Places Change Pagination",
  PlacesChangePois = "Places Change Pois",
  PlacesChangeOrder = "Places Change Order",
}
