import { SceneContentRating } from "decentraland-gatsby/dist/utils/api/Catalyst.types"

import { AggregateDestinationAttributes } from "../entities/Destination/types"

export const allPlacesWithAggregatedAttributes: AggregateDestinationAttributes[] =
  [
    {
      id: "214d5f61-4049-4109-b811-690813b1f7f0",
      title: "Genesis Plaza",
      description:
        "Decentraland's official spawn point and your #1 place to meet new people, hang out, and stay up to date with what's happening in our virtual world.",
      image: "https://localhost:8000/images/places/genesis_plaza.jpg",
      owner: null,
      positions: [
        "-1,-1",
        "-1,-2",
        "-1,-3",
        "-1,0",
        "-1,1",
        "-1,2",
        "-2,-1",
        "-2,-2",
        "-2,0",
        "-2,1",
        "-2,2",
        "-2,3",
        "-2,4",
        "-2,5",
        "-2,6",
        "-3,-1",
        "-3,-2",
        "-3,-3",
        "-3,0",
        "-3,1",
        "-3,2",
        "-3,3",
        "-3,4",
        "-3,5",
        "-3,6",
        "-4,-1",
        "-4,-2",
        "-4,-3",
        "-4,0",
        "-4,1",
        "-4,2",
        "-4,3",
        "-4,4",
        "-4,5",
        "-4,6",
        "-5,-1",
        "-5,-2",
        "-5,-3",
        "-5,0",
        "-5,1",
        "-5,2",
        "-5,3",
        "-5,4",
        "-5,5",
        "-5,6",
        "-6,-1",
        "-6,-2",
        "-6,0",
        "-6,1",
        "-6,2",
        "-6,3",
        "-6,4",
        "-6,5",
        "-6,6",
        "-7,-1",
        "-7,-2",
        "-7,0",
        "-7,1",
        "-7,2",
        "0,0",
        "1,0",
        "10,0",
        "2,0",
        "3,0",
        "4,0",
        "5,0",
        "6,0",
        "7,0",
        "8,0",
        "9,0",
      ],
      base_position: "0,0",
      contact_name: "Decentraland Foundation",
      contact_email: null,
      content_rating: SceneContentRating.RATING_PENDING,
      disabled: false,
      disabled_at: null,
      created_at: new Date("2022-11-11T04:53:07.000Z"),
      updated_at: new Date("2022-11-11T04:53:07.000Z"),
      favorites: 0,
      likes: 0,
      dislikes: 0,
      like_rate: 0.5,
      like_score: 0,
      highlighted: true,
      highlighted_image: "/images/places/genesis_plaza_banner.jpg",
      user_favorite: false,
      user_like: false,
      user_dislike: false,
      user_visits: 0,
      categories: [],
      world: false,
      world_name: null,
      deployed_at: new Date("2022-11-14T17:22:05.307Z"),
      is_private: false,
      creator_address: null,
      sdk: null,
      ranking: 0,
    },
    {
      id: "a7ce87fa-df3c-4a2f-bca6-bd2fe794d51a",
      title: "Test World",
      description: "Test World",
      image: "https://localhost:8000/images/places/genesis_plaza.jpg",
      owner: null,
      positions: [],
      base_position: "0,0",
      contact_name: "Decentraland Foundation",
      contact_email: null,
      content_rating: SceneContentRating.RATING_PENDING,
      disabled: false,
      disabled_at: null,
      created_at: new Date("2022-11-11T04:53:07.000Z"),
      updated_at: new Date("2022-11-11T04:53:07.000Z"),
      favorites: 0,
      likes: 0,
      dislikes: 0,
      like_rate: 0.6,
      like_score: 0,
      highlighted: true,
      highlighted_image: "/images/places/genesis_plaza_banner.jpg",
      user_favorite: false,
      user_like: false,
      user_dislike: false,
      user_visits: 0,
      categories: [],
      world: true,
      world_name: "test.dcl.eth",
      deployed_at: new Date("2022-11-14T17:22:05.307Z"),
      is_private: false,
      creator_address: null,
      sdk: null,
      ranking: 0,
    },
  ]
