name: API Docs

on:
  push:
    branches: [master]  
    paths: ['docs/**']

jobs:
  build:
    uses: decentraland/platform-actions/.github/workflows/apps-docs.yml@main
    with:
      api-spec-file: docs/openapi.yaml
      api-spec-name: places
      output-bundle-file: docs/openapi.yaml
    secrets: inherit     
