name: release

on:
  push:
    branches:
      - master

jobs:

  release:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf "ssh://git@github.com/"

      - name: node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.14.2
          registry-url: https://registry.npmjs.org/
          cache: 'npm'

      - name: installing
        run: npm ci

      - name: linters
        uses: wearerequired/lint-action@v1
        with:
          prettier: true
          prettier_extensions: ts,tsx,js,jsx,json,md,mdx,css
          continue_on_error: false
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: testing
        run: npm test -- --coverage

      - name: coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: setup envs
        run: echo .env

      - name: build image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: places
          tags: ${{ github.sha }} ${{ github.ref_name }} latest
          dockerfiles: |
            ./Dockerfile

      - name: Push To quay.io
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: quay.io/decentraland
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Print image url
        run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"

  # deployment:
  #   needs: [build-push]
  #   name: "Deploy to: dev"
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Trigger deployment
  #       id: deploy
  #       uses: decentraland/dcl-deploy-action@main
  #       with:
  #         dockerImage: "${{ needs.build-push.outputs.registry-path }}"
  #         serviceName: places
  #         env: dev
  #         token: ${{ secrets.GITHUB_TOKEN }}
